### PR TITLE
Fix: a few possible errors in the PlatformHandler.onError method

### LINKED ISSUE #1812: [BUG] Possible bug in the PlatformHandler.onError method
## Information

- **Version:** 6.107.2
- Packages:
  @tsed/common

https://github.com/tsedio/tsed/blob/86ce929f40ad2b77e2646d7c909ff731e667b21e/packages/platform/common/src/services/PlatformHandler.ts#L164-L186

This method has a few issues:
- the `$ctx` can be possibly `undefined`: on line 166 `$ctx.data = er;` but on line 173 there is a check that `$ctx` is defined
- on line 179 `$ctx` can be undefined`
- on line 173 there is a check that `next` is not defined but on line 184 we have a check again that `next` is defined. So we can clean up line 184

### PR DESCRIPTION
**Pull request by AlexDede**
## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Fix | No          |

---

Fixed: #1812

### CODE REVIEW

File: packages/platform/common/src/services/PlatformHandler.ts [hunk 1]
```diff
@@ -163,26 +163,29 @@ export class PlatformHandler {
...
         origin: er,
-        request_id: $ctx.id
+        request_id: $ctx?.id
       });
 
       return;
     }
 
-    return next && next(er);
+    return next(er);
```
Comment (Romakita) [inline packages/platform/common/src/services/PlatformHandler.ts:188]: next is not always given, it depend on how the handler have been built. Can you revert this change please ;)

**Review by Romakita — CHANGES_REQUESTED** [review]

File: packages/platform/common/src/services/PlatformHandler.ts (hunk 1 above)
Comment (AlexDede) [reply packages/platform/common/src/services/PlatformHandler.ts:188]: This method throws the error if `next` is not defined a few lines above

Comment (AlexDede) [reply packages/platform/common/src/services/PlatformHandler.ts:188]: So I can revert this line but in this case, I should remove

``` js
 if (!next) {
    throw er;
 }
```

But in this case, this can be a breaking change

Comment (Romakita) [reply packages/platform/common/src/services/PlatformHandler.ts:188]: You’ve right.

**Review by Romakita — APPROVED** [review]
